
# R/make_bdarma_impact_fn.R

#' Build BDARMA impact exhibits from three compact CSVs
#' @param root Root folder containing data/, figs/, and tables/ subfolders. Default "paper/impact_case".
#' @return Invisible normalized root path.
#' @export
make_bdarma_impact_artifacts <- function(root = "paper/impact_case") {
  data_dir   <- file.path(root, "data")
  figs_dir   <- file.path(root, "figs")
  tables_dir <- file.path(root, "tables")
  dirs <- c(data_dir, figs_dir, tables_dir)
  invisible(lapply(dirs, dir.create, recursive = TRUE, showWarnings = FALSE))

  save_png <- function(p, path, width = 1600, height = 1000, res = 200) {
    grDevices::png(path, width = width, height = height, res = res)
    print(p); grDevices::dev.off()
  }

  f_div <- file.path(data_dir, "caseA_divergence.csv")
  f_err <- file.path(data_dir, "caseA_errors.csv")
  f_stb <- file.path(data_dir, "caseB_stability.csv")

  # Create reproducible demo CSVs if missing
  synth_if_missing <- function() {
    if (!file.exists(f_div) || !file.exists(f_err) || !file.exists(f_stb)) {
      set.seed(20251115)
      months <- seq(as.Date("2022-01-01"), as.Date("2023-12-01"), by = "month")
      period <- ifelse(months < as.Date("2023-01-01"), "pre", "post")

      D <- 0.16 + stats::rnorm(length(months), sd = 0.015) +
        ifelse(period == "post", -0.01, 0)
      readr::write_csv(
        data.frame(month = months, D = round(pmax(0.12, D), 3), period = period),
        f_div
      )

      bins <- c("0-7","8-14","15-21")
      df_err <- do.call(rbind, lapply(bins, function(b) {
        base <- if (b == "0-7") 0.95 else if (b == "8-14") 1.05 else 1.18
        adj  <- ifelse(period == "post", -0.06, 0.0)
        data.frame(month = months, horizon_bin = b, period = period,
                   MASE = round(base + adj + stats::rnorm(length(months), sd = 0.03), 3))
      }))
      readr::write_csv(df_err, f_err)

      S <- 0.20 + stats::rnorm(length(months), sd = 0.02) +
        ifelse(period == "post", -0.05, 0)
      readr::write_csv(
        data.frame(month = months, S = round(pmax(0.05, S), 3), period = period),
        f_stb
      )
    }
  }
  synth_if_missing()

  div <- readr::read_csv(f_div, show_col_types = FALSE)
  err <- readr::read_csv(f_err, show_col_types = FALSE)
  stb <- readr::read_csv(f_stb, show_col_types = FALSE)

  # Divergence plot
  p_div <- ggplot2::ggplot(div, ggplot2::aes(x = month, y = D, color = period, group = 1)) +
    ggplot2::geom_line(linewidth = 0.9) +
    ggplot2::scale_x_date(date_breaks = "3 months", date_labels = "%b\n%Y") +
    ggplot2::labs(x = "Month", y = "Divergence D", title = "BDARMA monitoring: divergence pre vs post") +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1))
  save_png(p_div, file.path(figs_dir, "bdarma_divergence.png"))

  # Accuracy plot
  p_err <- ggplot2::ggplot(err, ggplot2::aes(x = month, y = MASE, color = period)) +
    ggplot2::geom_line() +
    ggplot2::facet_wrap(~ horizon_bin, ncol = 1, scales = "free_y") +
    ggplot2::scale_x_date(date_breaks = "3 months", date_labels = "%b\n%Y") +
    ggplot2::labs(x = "Month", y = "MASE", title = "BDARMA accuracy by horizon") +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1))
  save_png(p_err, file.path(figs_dir, "bdarma_accuracy.png"))

  # Stability plot
  p_stb <- ggplot2::ggplot(stb, ggplot2::aes(x = month, y = S, color = period, group = 1)) +
    ggplot2::geom_line(linewidth = 0.9) +
    ggplot2::scale_x_date(date_breaks = "3 months", date_labels = "%b\n%Y") +
    ggplot2::labs(x = "Month", y = "Forecast stability S", title = "BDARMA forecast stability") +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1))
  save_png(p_stb, file.path(figs_dir, "bdarma_stability.png"))

  # Pre vs post summary as LaTeX
  d_div <- div |>
    dplyr::summarise(
      pre   = mean(D[period == "pre"],  na.rm = TRUE),
      post  = mean(D[period == "post"], na.rm = TRUE),
      delta = post - pre
    )

  d_err <- err |>
    dplyr::group_by(horizon_bin) |>
    dplyr::summarise(
      pre   = mean(MASE[period == "pre"],  na.rm = TRUE),
      post  = mean(MASE[period == "post"], na.rm = TRUE),
      delta = post - pre,
      .groups = "drop"
    )

  d_stb <- stb |>
    dplyr::summarise(
      pre   = mean(S[period == "pre"],  na.rm = TRUE),
      post  = mean(S[period == "post"], na.rm = TRUE),
      delta = post - pre
    )

  tex <- c(
    "% Auto-generated by make_bdarma_impact_artifacts()",
    "\\begin{table}[t]",
    "\\centering",
    "\\caption{BDARMA monitoring: pre-post averages and deltas. Demo inputs in paper/impact_case/data/.}",
    "\\label{tab:bdarma}",
    "\\begin{tabular}{lrrr}",
    "\\toprule",
    "Metric & Pre & Post & Post - Pre \\\\",
    "\\midrule",
    sprintf("Divergence $D$ & %.3f & %.3f & %.3f \\\\", d_div$pre, d_div$post, d_div$delta),
    "\\midrule",
    "\\multicolumn{4}{l}{MASE by horizon} \\\\",
    paste(apply(d_err, 1, function(r) sprintf("%s & %.3f & %.3f & %.3f \\\\",
                                              r[1], as.numeric(r[2]), as.numeric(r[3]), as.numeric(r[4]))), collapse = "\n"),
    "\\midrule",
    sprintf("Stability $S$ & %.3f & %.3f & %.3f \\\\", d_stb$pre, d_stb$post, d_stb$delta),
    "\\bottomrule",
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(tex, con = file.path(tables_dir, "bdarma_summary.tex"))

  invisible(normalizePath(root))
}
